"""initial

Revision ID: 55f033911d3d
Revises: 418c3dcb6a3b
Create Date: 2024-08-02 12:19:46.666563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55f033911d3d'
down_revision: Union[str, None] = '418c3dcb6a3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anime', 'start_date',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('anime', 'end_date',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anime', 'end_date',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('anime', 'start_date',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
