"""initial

Revision ID: 71e48db355f1
Revises: 60fba79f57cb
Create Date: 2024-08-08 13:59:21.788392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '71e48db355f1'
down_revision: Union[str, None] = '60fba79f57cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anime', sa.Column('age_rating', sa.Enum('G', 'PG', 'R', 'R18', name='animeageratingenum'), nullable=False))
    op.add_column('anime', sa.Column('age_rating_guide', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anime', 'age_rating_guide')
    op.drop_column('anime', 'age_rating')
    # ### end Alembic commands ###
