"""initial

Revision ID: a3614891900e
Revises: a910ef4b7868
Create Date: 2024-08-02 12:23:28.784862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3614891900e'
down_revision: Union[str, None] = 'a910ef4b7868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anime', 'episode_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anime', 'episode_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
