"""initial

Revision ID: a910ef4b7868
Revises: 55f033911d3d
Create Date: 2024-08-02 12:21:58.655896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a910ef4b7868'
down_revision: Union[str, None] = '55f033911d3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anime', 'status',
               existing_type=postgresql.ENUM('CURRENT', 'FINISHED', 'TBA', 'UPCOMING', 'UNRELEASED', name='animestatusenum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anime', 'status',
               existing_type=postgresql.ENUM('CURRENT', 'FINISHED', 'TBA', 'UPCOMING', 'UNRELEASED', name='animestatusenum'),
               nullable=False)
    # ### end Alembic commands ###
