"""initial

Revision ID: bcab65e077ab
Revises: 26b42c0558ae
Create Date: 2024-08-02 12:31:32.536514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bcab65e077ab'
down_revision: Union[str, None] = '26b42c0558ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anime', 'status',
               existing_type=postgresql.ENUM('CURRENT', 'FINISHED', 'TBA', 'UPCOMING', 'UNRELEASED', name='animestatusenum'),
               nullable=False)
    op.alter_column('anime', 'show_type',
               existing_type=postgresql.ENUM('ONA', 'OVA', 'TV', 'MOVIE', 'MUSIC', 'SPECIAL', name='animeshowtypeenum'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anime', 'show_type',
               existing_type=postgresql.ENUM('ONA', 'OVA', 'TV', 'MOVIE', 'MUSIC', 'SPECIAL', name='animeshowtypeenum'),
               nullable=True)
    op.alter_column('anime', 'status',
               existing_type=postgresql.ENUM('CURRENT', 'FINISHED', 'TBA', 'UPCOMING', 'UNRELEASED', name='animestatusenum'),
               nullable=True)
    # ### end Alembic commands ###
