"""initial

Revision ID: 26b42c0558ae
Revises: a3614891900e
Create Date: 2024-08-02 12:24:42.224098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26b42c0558ae'
down_revision: Union[str, None] = 'a3614891900e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anime', 'show_type',
               existing_type=postgresql.ENUM('ONA', 'OVA', 'TV', 'MOVIE', 'MUSIC', 'SPECIAL', name='animeshowtypeenum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anime', 'show_type',
               existing_type=postgresql.ENUM('ONA', 'OVA', 'TV', 'MOVIE', 'MUSIC', 'SPECIAL', name='animeshowtypeenum'),
               nullable=False)
    # ### end Alembic commands ###
